# Generated by Django 3.1.1 on 2020-10-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresito_api', '0002_materiaprima'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
