# Generated by Django 3.1.1 on 2020-10-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresito_api', '0005_auto_20201029_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='fecha',
            new_name='date_joined',
        ),
    ]
