# Generated by Django 3.1.1 on 2020-10-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresito_api', '0006_auto_20201029_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='descripcion',
            new_name='description',
        ),
    ]
