# Generated by Django 3.1.1 on 2020-10-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresito_api', '0007_auto_20201029_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='description',
            new_name='descripcion',
        ),
    ]
