# Generated by Django 3.1.1 on 2020-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresito_api', '0008_auto_20201029_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=40)),
                ('descripcionMp', models.CharField(max_length=10)),
                ('cantMprimaUtilizada', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=40)),
                ('cliente', models.CharField(max_length=10)),
                ('ordenDeTrabajo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionP', models.CharField(max_length=40)),
                ('materiaPriUtilizada', models.CharField(max_length=40)),
                ('cantiMatPriUtilizada', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('precioUnitario', models.IntegerField(default=0)),
                ('precioTotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='members',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='members',
            field=models.ManyToManyField(through='impresito_api.Membership', to='impresito_api.MateriaPrima'),
        ),
    ]
