# Generated by Django 3.1.1 on 2020-10-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresito_api', '0011_auto_20201030_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='productox',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idventa',
        ),
    ]
